/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asclepio.user.common.view.edit;

import asclepio.server.funcs.WriterCommon;
import asclepio.server.funcs.ReaderCommon;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caio
 */
public class Medicament extends javax.swing.JInternalFrame {

    ReaderCommon leitura;
    WriterCommon escrita;
    String values;
    String CPF;

    /**
     * Creates new form Medicamentos
     */
    public Medicament(String CPF) throws IOException {
        initComponents();
        escrita = new WriterCommon();
        leitura = new ReaderCommon();

        this.CPF = CPF;
        getValue();
        setImage();
    }

    public void setImage() {
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/main/icons/hospital.png")));
    }

    public void getValue() throws IOException {
        values = leitura.leituraMedicamentos(CPF);
        if (!values.isEmpty()) {
            setValue();
        }
    }

    public void setValue() {
        String value[] = values.split("#");
        DefaultTableModel tableMedicamentos = (DefaultTableModel) jTableMedicamentos.getModel();

        for (int i = 0; i < value.length; i++) {
            String value_split[] = value[i].split(";");

            tableMedicamentos.addRow(new Object[]{value_split[0], value_split[1]});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jButtonAlterar = new javax.swing.JButton();
        medicamentos = new javax.swing.JTextField();
        button_Add_Medicamentos = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMedicamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Medicamentos");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamentos"));

        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/common/icons/save.png"))); // NOI18N
        jButtonAlterar.setText("Salvar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        button_Add_Medicamentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_Add_Medicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/common/icons/add.png"))); // NOI18N
        button_Add_Medicamentos.setText("Adicionar");
        button_Add_Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Add_MedicamentosActionPerformed(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/common/icons/delete.png"))); // NOI18N
        jButtonDelete.setText("Deletar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTableMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamentos", "Verificação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableMedicamentos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("V = Alergia Verificada;  X= Alergia NÃO Verificada;");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(medicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_Add_Medicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Add_Medicamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_Add_MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Add_MedicamentosActionPerformed
        DefaultTableModel tableMedicamentos = (DefaultTableModel) jTableMedicamentos.getModel();
        Object[] medic = {medicamentos.getText(), "X"};
        tableMedicamentos.addRow(medic);
        medicamentos.setText("");
    }//GEN-LAST:event_button_Add_MedicamentosActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DefaultTableModel tableMedicamentos = (DefaultTableModel) jTableMedicamentos.getModel();
        if (jTableMedicamentos.getSelectedRow() >= 0) {
            infoVerificada(tableMedicamentos, jTableMedicamentos.getSelectedRow());
        } else {

            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    void infoVerificada(DefaultTableModel tableMedicamentos, int i) {
        Object obj = jTableMedicamentos.getValueAt(i, 1);
        if (obj.toString().equals("V")) {
            JOptionPane.showMessageDialog(null, "Favor ir ao medico para remover essa informação");
        } else {
            tableMedicamentos.removeRow(jTableMedicamentos.getSelectedRow());
            jTableMedicamentos.setModel(tableMedicamentos);
        }

    }
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        DefaultTableModel tableMedicamentos = (DefaultTableModel) jTableMedicamentos.getModel();

        Object obj;
        Object obj2;
        ArrayList<String> medicamentos = new ArrayList<String>();
        for (int i = 0; i < tableMedicamentos.getRowCount(); i++) {

            obj = jTableMedicamentos.getValueAt(i, 0);
            obj2 = jTableMedicamentos.getValueAt(i, 1);
            medicamentos.add(obj.toString() + ";" + obj2.toString());

        }
        try {
            escrita.escreveMedicamentos(CPF, medicamentos, true);
            JOptionPane.showMessageDialog(null, "Medicamentos alterados com sucesso");
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Medicament.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Add_Medicamentos;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableMedicamentos;
    private javax.swing.JTextField medicamentos;
    // End of variables declaration//GEN-END:variables
}
