/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asclepio.user.common.view;

import asclepio.server.funcs.ReaderMedicalInformation;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caio
 */
public class MedicalInformationResult extends javax.swing.JInternalFrame {

    ReaderMedicalInformation leitura;
    String medico;

    /**
     * Creates new form MedicalInformationResult
     */
    public MedicalInformationResult(String tMedico) throws IOException {
        initComponents();
        title = tMedico + "s";
        medico = tMedico;
        leitura = new ReaderMedicalInformation();
        setValues();
        setImage();
    }

    public void setImage() {
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/main/icons/hospital.png")));
    }

    public void adicionaNaTabelaQuatroVariaveis(String value[], DefaultTableModel table) {
        for (int i = 0; i < value.length; i++) {
            String value_split[] = value[i].split(";");

            table.addRow(new Object[]{value_split[0], value_split[1], value_split[2], value_split[3]});

        }
    }

    public void setValues() throws IOException {
        String values = "";
        values = leitura.leituraMedicos(medico);
        if (!values.isEmpty()) {
            String value[] = values.split("#");
            DefaultTableModel tableMedical = (DefaultTableModel) jTableMedical.getModel();

            adicionaNaTabelaQuatroVariaveis(value, tableMedical);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedical = new javax.swing.JTable();

        setClosable(true);

        jTableMedical.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableMedical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "Tempo de Profissão", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMedical);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedical;
    // End of variables declaration//GEN-END:variables
}
