/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asclepio.server.view;

import asclepio.user.common.view.RegisterUserCommon;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Caio
 */
public class UserWorkspaceServer extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserWorkspaceServer
     */
    public UserWorkspaceServer() {
        initComponents();
        setImage();
    }

    public void setImage() {
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/main/icons/hospital.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarEspecial = new javax.swing.JButton();
        jButtonCadastrarCommon = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Menu Server");

        jButtonCadastrarEspecial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadastrarEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/server/icons/id-card.png"))); // NOI18N
        jButtonCadastrarEspecial.setText("Cadastrar Usuario Profissional");
        jButtonCadastrarEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEspecialActionPerformed(evt);
            }
        });

        jButtonCadastrarCommon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadastrarCommon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/server/icons/patient.png"))); // NOI18N
        jButtonCadastrarCommon.setText("Cadastrar Usuario Comum");
        jButtonCadastrarCommon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarCommonActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/common/icons/exit(1).png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/server/icons/information.png"))); // NOI18N
        jButton1.setText("Cadastrar Informações Sobre Medicos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastrarEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastrarCommon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonCadastrarEspecial)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarCommon)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        try {
            MainMenu_Server.getInstancia().id_logado = "";
            MainMenu_Server.getInstancia().tela_login = false;
            MainMenu_Server.getInstancia().flushPane();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceServer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastrarEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEspecialActionPerformed
        RegisterUserProfissional user = new RegisterUserProfissional();
        try {
            MainMenu_Server.getDesktopPane().add(user);
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        user.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarEspecialActionPerformed

    private void jButtonCadastrarCommonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCommonActionPerformed
        RegisterUserCommon registro = new RegisterUserCommon(true);
        try {
            MainMenu_Server.getDesktopPane().add(registro);
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        registro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarCommonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegisterMedicalInformation registro = new RegisterMedicalInformation();
        try {
            MainMenu_Server.getDesktopPane().add(registro);
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        registro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrarCommon;
    private javax.swing.JButton jButtonCadastrarEspecial;
    private javax.swing.JButton jButtonSair;
    // End of variables declaration//GEN-END:variables
}
