/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asclepio.user.profissional.view;

import asclepio.server.funcs.ReaderProfissional;
import asclepio.user.common.view.RegisterUserCommon;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Caio
 */
public class UserWorkspaceProfissionalReceptionist extends javax.swing.JInternalFrame {

    String id;
    ReaderProfissional leitura = new ReaderProfissional();

    /**
     * Creates new form UserWorkspaceEspecialRecepcionista
     */
    public UserWorkspaceProfissionalReceptionist(String id) throws IOException {
        initComponents();
        this.id = id;
        setAtributos(id);
        title = "Menu de Usuario (" + jNome.getText() + ")";
        setImage();
    }

    public void setImage() {
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/main/icons/hospital.png")));
    }

    void setAtributos(String id) throws IOException {
        String info[] = leitura.getInformacoes(id);
        jNome.setText(info[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarCommon = new javax.swing.JButton();
        jNome = new javax.swing.JLabel();

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/common/icons/exit(1).png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/profissional/icons/magnifying-glass.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/profissional/icons/girl.png"))); // NOI18N

        jButtonCadastrarCommon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCadastrarCommon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asclepio/user/profissional/icons/patient.png"))); // NOI18N
        jButtonCadastrarCommon.setText("Cadastrar Usuario");
        jButtonCadastrarCommon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCadastrarCommon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarCommonActionPerformed(evt);
            }
        });

        jNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNome.setText("nome");
        jNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonCadastrarCommon, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButtonPesquisar)
                .addGap(44, 44, 44)
                .addComponent(jButtonCadastrarCommon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        try {
            MainMenu_Profissional.getInstancia().id_logado = "";
            MainMenu_Profissional.getInstancia().tela_login = false;
            this.dispose();
            MainMenu_Profissional.getInstancia().flushPane();
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceProfissionalReceptionist.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        SearchReceptionist pesquisa = new SearchReceptionist(this);
        try {
            MainMenu_Profissional.getDesktopPane().add(pesquisa);

            pesquisa.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceProfissionalReceptionist.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCadastrarCommonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCommonActionPerformed
        RegisterUserCommon registro = new RegisterUserCommon(true);
        try {
            MainMenu_Profissional.getDesktopPane().add(registro);
        } catch (IOException ex) {
            Logger.getLogger(UserWorkspaceProfissionalReceptionist.class.getName()).log(Level.SEVERE, null, ex);
        }
        registro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarCommonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCommon;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNome;
    // End of variables declaration//GEN-END:variables
}
